# Generated by Django 6.0.2 on 2026-03-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
    ]
