# Generated by Django 6.0.2 on 2026-03-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='exercises_solved',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
