# Generated by Django 6.0.2 on 2026-03-16 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_exercises_solved_profile_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.CreateModel(
            name='WorldProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_index', models.PositiveIntegerField()),
                ('exercises_solved', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_progress', to='api.profile')),
            ],
            options={
                'unique_together': {('profile', 'world_index')},
            },
        ),
    ]
