# Generated by Django 6.0.2 on 2026-03-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldprogress',
            name='mistakes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
