# Generated by Django 6.0.3 on 2026-03-04 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('alt', models.CharField(default='World Image', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='worlds/')),
                ('default_status', models.CharField(default='locked', max_length=20)),
                ('required_level', models.IntegerField(default=1)),
                ('gems', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6b5bff', max_length=20)),
                ('secondary_color', models.CharField(default='#9d7aff', max_length=20)),
                ('background_gradient', models.TextField(default='radial-gradient(ellipse at top, #0a0a3a, #03031a, #000008)')),
                ('star_color', models.CharField(default='#ffffff', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gems', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
                ('current_world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_users', to='games.world')),
                ('unlocked_worlds', models.ManyToManyField(blank=True, related_name='unlocked_by_users', to='games.world')),
            ],
        ),
    ]
